
const mongoose = require("mongoose");
const dotenv = require("dotenv");
dotenv.config();

const Product = require("../models/Product");

const products = [
  {
    name: "Kashmiri Red Chilli Powder",
    description: "Premium quality Kashmiri chilli - vibrant red color, mild heat, perfect for tandoori dishes and curries.",
    price: 149,
    originalPrice: 199,
    image: "https://images.pexels.com/photos/277253/pexels-photo-277253.jpeg",
    category: "Chilli",
    stock: 100,
    rating: 4.5,
    numReviews: 12,
    weight: "200g",
    origin: "Kashmir",
    isFeatured: true,
  },
  {
    name: "Turmeric Powder (Haldi)",
    description: "Pure organic turmeric with high curcumin content. Anti-inflammatory and golden color for all curries.",
    price: 89,
    originalPrice: 120,
    image: "https://images.pexels.com/photos/1128684/pexels-photo-1128684.jpeg",
    category: "Turmeric",
    stock: 200,
    rating: 4.8,
    numReviews: 25,
    weight: "250g",
    origin: "Erode, Tamil Nadu",
    isFeatured: true,
  },
  {
    name: "Garam Masala Blend",
    description: "Aromatic mix of 12 spices - cinnamon, cardamom, cloves, black pepper. Freshly ground for maximum flavor.",
    price: 199,
    originalPrice: 249,
    image: "https://images.pexels.com/photos/4061520/pexels-photo-4061520.jpeg",
    category: "Blended",
    stock: 80,
    rating: 4.7,
    numReviews: 18,
    weight: "100g",
    origin: "Rajasthan",
    isFeatured: true,
  },
  {
    name: "Cumin Seeds (Jeera)",
    description: "Whole cumin seeds with intense earthy aroma. Essential for tadka, rice dishes and Indian bread.",
    price: 79,
    originalPrice: 99,
    image: "https://images.pexels.com/photos/5639975/pexels-photo-5639975.jpeg",
    category: "Seeds",
    stock: 150,
    rating: 4.6,
    numReviews: 30,
    weight: "200g",
    origin: "Gujarat",
    isFeatured: false,
  },
  {
    name: "Coriander Powder (Dhania)",
    description: "Finely ground coriander seeds with citrusy flavor. Base spice for most Indian gravies.",
    price: 69,
    originalPrice: 89,
    image: "https://images.pexels.com/photos/5639976/pexels-photo-5639976.jpeg",
    category: "Powder",
    stock: 120,
    rating: 4.4,
    numReviews: 15,
    weight: "250g",
    origin: "Rajasthan",
    isFeatured: false,
  },
  {
    name: "Black Pepper Whole",
    description: "Premium Malabar black pepper - the king of spices. Bold, pungent flavor for any cuisine.",
    price: 229,
    originalPrice: 299,
    image: "https://images.pexels.com/photos/5639980/pexels-photo-5639980.jpeg",
    category: "Pepper",
    stock: 60,
    rating: 4.9,
    numReviews: 22,
    weight: "100g",
    origin: "Kerala",
    isFeatured: true,
  },
  {
    name: "Cardamom Green (Elaichi)",
    description: "Fragrant green cardamom pods from Kerala. Perfect for chai, desserts and biryani.",
    price: 349,
    originalPrice: 449,
    image: "https://images.pexels.com/photos/5639979/pexels-photo-5639979.jpeg",
    category: "Seeds",
    stock: 50,
    rating: 4.8,
    numReviews: 19,
    weight: "50g",
    origin: "Kerala",
    isFeatured: false,
  },
  {
    name: "Biryani Masala Special",
    description: "Restaurant-style biryani masala blend. Makes every biryani authentic and aromatic.",
    price: 179,
    originalPrice: 229,
    image: "https://images.pexels.com/photos/5639977/pexels-photo-5639977.jpeg",
    category: "Blended",
    stock: 90,
    rating: 4.6,
    numReviews: 28,
    weight: "150g",
    origin: "Hyderabad",
    isFeatured: true,
  },
  {
    name: "Hot Red Chilli Powder",
    description: "Extra spicy chilli powder for bold flavor and heat in Indian dishes.",
    price: 139,
    originalPrice: 179,
    image: "https://images.pexels.com/photos/277253/pexels-photo-277253.jpeg",
    category: "Chilli",
    stock: 90,
    rating: 4.4,
    numReviews: 10,
    weight: "200g",
    origin: "Andhra Pradesh",
    isFeatured: false,
  },
  {
    name: "Byadgi Chilli Powder",
    description: "Famous Byadgi chilli known for deep red color and mild spice.",
    price: 159,
    originalPrice: 199,
    image: "https://images.pexels.com/photos/5639981/pexels-photo-5639981.jpeg",
    category: "Chilli",
    stock: 80,
    rating: 4.6,
    numReviews: 14,
    weight: "200g",
    origin: "Karnataka",
    isFeatured: true,
  },
  {
    name: "Organic Red Chilli Powder",
    description: "100% organic chilli powder with no chemicals or additives.",
    price: 169,
    originalPrice: 219,
    image: "https://images.pexels.com/photos/1128684/pexels-photo-1128684.jpeg",
    category: "Chilli",
    stock: 70,
    rating: 4.7,
    numReviews: 18,
    weight: "200g",
    origin: "India",
    isFeatured: false,
  },
  {
    name: "Smoked Chilli Powder",
    description: "Smoky flavored chilli powder for BBQ and grilled recipes.",
    price: 179,
    originalPrice: 229,
    image: "https://images.pexels.com/photos/4061520/pexels-photo-4061520.jpeg",
    category: "Chilli",
    stock: 60,
    rating: 4.5,
    numReviews: 9,
    weight: "150g",
    origin: "India",
    isFeatured: false,
  },
  {
    name: "Chilli Flakes",
    description: "Crushed red chilli flakes perfect for pizza, pasta and snacks.",
    price: 99,
    originalPrice: 129,
    image: "https://images.pexels.com/photos/5639975/pexels-photo-5639975.jpeg",
    category: "Chilli",
    stock: 110,
    rating: 4.3,
    numReviews: 11,
    weight: "100g",
    origin: "India",
    isFeatured: false,
  },
  {
    name: "Premium Chilli Powder",
    description: "Finely ground chilli powder with rich aroma and color.",
    price: 149,
    originalPrice: 189,
    image: "https://images.pexels.com/photos/5639976/pexels-photo-5639976.jpeg",
    category: "Chilli",
    stock: 95,
    rating: 4.6,
    numReviews: 13,
    weight: "200g",
    origin: "India",
    isFeatured: true,
  },
  {
    name: "Extra Hot Chilli Powder",
    description: "Very spicy chilli powder for extreme heat lovers.",
    price: 159,
    originalPrice: 199,
    image: "https://images.pexels.com/photos/5639980/pexels-photo-5639980.jpeg",
    category: "Chilli",
    stock: 75,
    rating: 4.7,
    numReviews: 16,
    weight: "200g",
    origin: "Rajasthan",
    isFeatured: false,
  },
  {
    name: "Mild Chilli Powder",
    description: "Low heat chilli powder with rich color, ideal for kids and mild recipes.",
    price: 129,
    originalPrice: 169,
    image: "https://images.pexels.com/photos/5639979/pexels-photo-5639979.jpeg",
    category: "Chilli",
    stock: 85,
    rating: 4.2,
    numReviews: 8,
    weight: "200g",
    origin: "India",
    isFeatured: false,
  },
  {
    name: "Desi Red Chilli Powder",
    description: "Traditional Indian chilli powder used in everyday cooking.",
    price: 119,
    originalPrice: 149,
    image: "https://images.pexels.com/photos/5639977/pexels-photo-5639977.jpeg",
    category: "Chilli",
    stock: 120,
    rating: 4.4,
    numReviews: 12,
    weight: "200g",
    origin: "India",
    isFeatured: true,
  },
  {
    name: "Turmeric Powder Premium",
    description: "High-grade turmeric powder with strong aroma and rich color. Ideal for daily cooking.",
    price: 95,
    originalPrice: 130,
    image: "https://images.pexels.com/photos/1128684/pexels-photo-1128684.jpeg",
    category: "Turmeric",
    stock: 180,
    rating: 4.6,
    numReviews: 18,
    weight: "250g",
    origin: "Erode, Tamil Nadu",
    isFeatured: true,
  },
  {
    name: "Organic Haldi Powder",
    description: "Certified organic turmeric with natural curcumin. No chemicals or additives.",
    price: 110,
    originalPrice: 150,
    image: "https://images.pexels.com/photos/4061520/pexels-photo-4061520.jpeg",
    category: "Turmeric",
    stock: 150,
    rating: 4.7,
    numReviews: 22,
    weight: "250g",
    origin: "Salem, Tamil Nadu",
    isFeatured: false,
  },
  {
    name: "Lakadong Turmeric Powder",
    description: "Famous Lakadong turmeric with very high curcumin content and strong medicinal value.",
    price: 180,
    originalPrice: 220,
    image: "https://images.pexels.com/photos/5639981/pexels-photo-5639981.jpeg",
    category: "Turmeric",
    stock: 120,
    rating: 4.9,
    numReviews: 30,
    weight: "200g",
    origin: "Meghalaya",
    isFeatured: true,
  },
  {
    name: "Farm Fresh Haldi Powder",
    description: "Direct from farms, freshly ground turmeric retaining natural oils and flavor.",
    price: 85,
    originalPrice: 120,
    image: "https://images.pexels.com/photos/5639975/pexels-photo-5639975.jpeg",
    category: "Turmeric",
    stock: 200,
    rating: 4.5,
    numReviews: 15,
    weight: "250g",
    origin: "Andhra Pradesh",
    isFeatured: false,
  },
  {
    name: "Golden Turmeric Powder",
    description: "Bright golden turmeric for rich color and authentic taste in Indian dishes.",
    price: 90,
    originalPrice: 125,
    image: "https://images.pexels.com/photos/5639976/pexels-photo-5639976.jpeg",
    category: "Turmeric",
    stock: 170,
    rating: 4.6,
    numReviews: 19,
    weight: "250g",
    origin: "Tamil Nadu",
    isFeatured: false,
  },
  {
    name: "Curcumin Rich Haldi",
    description: "Special turmeric powder with high curcumin content for health benefits.",
    price: 140,
    originalPrice: 180,
    image: "https://images.pexels.com/photos/1128684/pexels-photo-1128684.jpeg",
    category: "Turmeric",
    stock: 130,
    rating: 4.8,
    numReviews: 27,
    weight: "200g",
    origin: "Kerala",
    isFeatured: true,
  },
  {
    name: "Desi Haldi Powder",
    description: "Traditional Indian turmeric with earthy flavor and natural fragrance.",
    price: 80,
    originalPrice: 110,
    image: "https://images.pexels.com/photos/5639980/pexels-photo-5639980.jpeg",
    category: "Turmeric",
    stock: 220,
    rating: 4.4,
    numReviews: 12,
    weight: "250g",
    origin: "Maharashtra",
    isFeatured: false,
  },
  {
    name: "Pure Village Turmeric",
    description: "Hand-processed turmeric powder sourced from village farms.",
    price: 100,
    originalPrice: 135,
    image: "https://images.pexels.com/photos/5639979/pexels-photo-5639979.jpeg",
    category: "Turmeric",
    stock: 140,
    rating: 4.6,
    numReviews: 20,
    weight: "250g",
    origin: "Karnataka",
    isFeatured: false,
  },
  {
    name: "Premium Erode Haldi",
    description: "Top-quality Erode turmeric known for its strong color and purity.",
    price: 120,
    originalPrice: 160,
    image: "https://images.pexels.com/photos/5639977/pexels-photo-5639977.jpeg",
    category: "Turmeric",
    stock: 160,
    rating: 4.8,
    numReviews: 25,
    weight: "250g",
    origin: "Erode, Tamil Nadu",
    isFeatured: true,
  },
  {
    name: "Natural Turmeric Powder",
    description: "100% natural turmeric powder with no preservatives or additives.",
    price: 88,
    originalPrice: 120,
    image: "https://images.pexels.com/photos/4061520/pexels-photo-4061520.jpeg",
    category: "Turmeric",
    stock: 190,
    rating: 4.5,
    numReviews: 16,
    weight: "250g",
    origin: "Telangana",
    isFeatured: false,
  },
  {
    name: "Ayurvedic Haldi Powder",
    description: "Turmeric used in Ayurveda for immunity and healing properties.",
    price: 135,
    originalPrice: 170,
    image: "https://images.pexels.com/photos/5639981/pexels-photo-5639981.jpeg",
    category: "Turmeric",
    stock: 110,
    rating: 4.7,
    numReviews: 21,
    weight: "200g",
    origin: "Kerala",
    isFeatured: true,
  },
  {
    name: "Strong Flavor Turmeric",
    description: "Bold flavored turmeric powder ideal for curries and masala blends.",
    price: 92,
    originalPrice: 125,
    image: "https://images.pexels.com/photos/5639975/pexels-photo-5639975.jpeg",
    category: "Turmeric",
    stock: 175,
    rating: 4.6,
    numReviews: 18,
    weight: "250g",
    origin: "Gujarat",
    isFeatured: false,
  },
  {
    name: "Garam Masala Premium",
    description: "Aromatic blend of whole spices for rich flavor in curries and gravies.",
    price: 120,
    originalPrice: 160,
    image: "https://images.pexels.com/photos/5639976/pexels-photo-5639976.jpeg",
    category: "Blended Masala",
    stock: 150,
    rating: 4.7,
    numReviews: 28,
    weight: "200g",
    origin: "Delhi",
    isFeatured: true,
  },
  {
    name: "Chicken Masala",
    description: "Perfect spice mix for flavorful and spicy chicken dishes.",
    price: 110,
    originalPrice: 145,
    image: "https://images.pexels.com/photos/277253/pexels-photo-277253.jpeg",
    category: "Blended Masala",
    stock: 180,
    rating: 4.6,
    numReviews: 20,
    weight: "200g",
    origin: "Punjab",
    isFeatured: true,
  },
  {
    name: "Paneer Butter Masala Mix",
    description: "Creamy and rich masala blend for delicious paneer recipes.",
    price: 130,
    originalPrice: 170,
    image: "https://images.pexels.com/photos/4061520/pexels-photo-4061520.jpeg",
    category: "Blended Masala",
    stock: 120,
    rating: 4.8,
    numReviews: 24,
    weight: "200g",
    origin: "Uttar Pradesh",
    isFeatured: false,
  },
  {
    name: "Biryani Masala",
    description: "Authentic spice mix for aromatic and flavorful biryani.",
    price: 140,
    originalPrice: 180,
    image: "https://images.pexels.com/photos/1128684/pexels-photo-1128684.jpeg",
    category: "Blended Masala",
    stock: 160,
    rating: 4.9,
    numReviews: 35,
    weight: "250g",
    origin: "Hyderabad",
    isFeatured: true,
  },
  {
    name: "Chole Masala",
    description: "Tangy and spicy masala for Punjabi-style chole.",
    price: 100,
    originalPrice: 130,
    image: "https://images.pexels.com/photos/5639980/pexels-photo-5639980.jpeg",
    category: "Blended Masala",
    stock: 200,
    rating: 4.5,
    numReviews: 18,
    weight: "200g",
    origin: "Punjab",
    isFeatured: false,
  },
  {
    name: "Sambar Masala",
    description: "South Indian spice mix for authentic sambar taste.",
    price: 90,
    originalPrice: 120,
    image: "https://images.pexels.com/photos/5639979/pexels-photo-5639979.jpeg",
    category: "Blended Masala",
    stock: 170,
    rating: 4.6,
    numReviews: 22,
    weight: "200g",
    origin: "Tamil Nadu",
    isFeatured: false,
  },
  {
    name: "Pav Bhaji Masala",
    description: "Spicy and tangy masala for street-style pav bhaji.",
    price: 95,
    originalPrice: 125,
    image: "https://images.pexels.com/photos/5639977/pexels-photo-5639977.jpeg",
    category: "Blended Masala",
    stock: 190,
    rating: 4.7,
    numReviews: 21,
    weight: "200g",
    origin: "Maharashtra",
    isFeatured: true,
  },
  {
    name: "Kitchen King Masala",
    description: "All-purpose masala blend for vegetables and curries.",
    price: 105,
    originalPrice: 140,
    image: "https://images.pexels.com/photos/1128684/pexels-photo-1128684.jpeg",
    category: "Blended Masala",
    stock: 160,
    rating: 4.6,
    numReviews: 19,
    weight: "200g",
    origin: "Rajasthan",
    isFeatured: false,
  },
  {
    name: "Fish Curry Masala",
    description: "Special blend for coastal-style fish curry.",
    price: 125,
    originalPrice: 160,
    image: "https://images.pexels.com/photos/277253/pexels-photo-277253.jpeg",
    category: "Blended Masala",
    stock: 140,
    rating: 4.7,
    numReviews: 23,
    weight: "200g",
    origin: "Kerala",
    isFeatured: true,
  },
  {
    name: "Mutton Masala",
    description: "Rich and spicy masala for mutton dishes.",
    price: 135,
    originalPrice: 175,
    image: "https://images.pexels.com/photos/4061520/pexels-photo-4061520.jpeg",
    category: "Blended Masala",
    stock: 130,
    rating: 4.8,
    numReviews: 26,
    weight: "200g",
    origin: "Lucknow",
    isFeatured: true,
  },
  {
    name: "Rasam Powder",
    description: "Tangy and peppery mix for traditional rasam.",
    price: 85,
    originalPrice: 110,
    image: "https://images.pexels.com/photos/5639975/pexels-photo-5639975.jpeg",
    category: "Blended Masala",
    stock: 200,
    rating: 4.5,
    numReviews: 17,
    weight: "200g",
    origin: "Tamil Nadu",
    isFeatured: false,
  },
  {
    name: "Tandoori Masala",
    description: "Smoky spice blend for tandoori dishes and grilling.",
    price: 115,
    originalPrice: 150,
    image: "https://images.pexels.com/photos/5639976/pexels-photo-5639976.jpeg",
    category: "Blended Masala",
    stock: 150,
    rating: 4.7,
    numReviews: 20,
    weight: "200g",
    origin: "Punjab",
    isFeatured: true,
  },
  {
    name: "Egg Curry Masala",
    description: "Perfect masala mix for spicy egg curry.",
    price: 90,
    originalPrice: 120,
    image: "https://images.pexels.com/photos/5639980/pexels-photo-5639980.jpeg",
    category: "Blended Masala",
    stock: 180,
    rating: 4.6,
    numReviews: 16,
    weight: "200g",
    origin: "Bihar",
    isFeatured: false,
  },
  {
    name: "Dal Tadka Masala",
    description: "Flavorful masala for dal fry and tadka.",
    price: 95,
    originalPrice: 125,
    image: "https://images.pexels.com/photos/1128684/pexels-photo-1128684.jpeg",
    category: "Blended Masala",
    stock: 210,
    rating: 4.5,
    numReviews: 14,
    weight: "200g",
    origin: "Gujarat",
    isFeatured: false,
  },
  {
    name: "Butter Chicken Masala",
    description: "Creamy and mildly spiced blend for butter chicken.",
    price: 140,
    originalPrice: 180,
    image: "https://images.pexels.com/photos/277253/pexels-photo-277253.jpeg",
    category: "Blended Masala",
    stock: 140,
    rating: 4.9,
    numReviews: 32,
    weight: "200g",
    origin: "Delhi",
    isFeatured: true,
  },
  {
    name: "Cumin Seeds (Jeera)",
    description: "Aromatic cumin seeds used for tempering and enhancing flavor in Indian dishes.",
    price: 95,
    originalPrice: 130,
    image: "https://images.pexels.com/photos/5639981/pexels-photo-5639981.jpeg",
    category: "Seeds",
    stock: 200,
    rating: 4.7,
    numReviews: 30,
    weight: "200g",
    origin: "Rajasthan",
    isFeatured: true,
  },
  {
    name: "Mustard Seeds (Rai)",
    description: "Small black mustard seeds perfect for tadka and pickles.",
    price: 60,
    originalPrice: 90,
    image: "https://images.pexels.com/photos/277253/pexels-photo-277253.jpeg",
    category: "Seeds",
    stock: 250,
    rating: 4.6,
    numReviews: 22,
    weight: "200g",
    origin: "Uttar Pradesh",
    isFeatured: false,
  },
  {
    name: "Fennel Seeds (Saunf)",
    description: "Sweet and aromatic fennel seeds for digestion and mouth freshener.",
    price: 85,
    originalPrice: 120,
    image: "https://images.pexels.com/photos/4061520/pexels-photo-4061520.jpeg",
    category: "Seeds",
    stock: 180,
    rating: 4.8,
    numReviews: 28,
    weight: "200g",
    origin: "Gujarat",
    isFeatured: true,
  },
  {
    name: "Fenugreek Seeds (Methi)",
    description: "Bitter-sweet seeds used in curries and for health benefits.",
    price: 70,
    originalPrice: 100,
    image: "https://images.pexels.com/photos/1128684/pexels-photo-1128684.jpeg",
    category: "Seeds",
    stock: 210,
    rating: 4.5,
    numReviews: 18,
    weight: "200g",
    origin: "Madhya Pradesh",
    isFeatured: false,
  },
  {
    name: "Carom Seeds (Ajwain)",
    description: "Strong flavored seeds used for digestion and cooking.",
    price: 90,
    originalPrice: 130,
    image: "https://images.pexels.com/photos/5639980/pexels-photo-5639980.jpeg",
    category: "Seeds",
    stock: 160,
    rating: 4.6,
    numReviews: 20,
    weight: "200g",
    origin: "Rajasthan",
    isFeatured: true,
  },
  {
    name: "Nigella Seeds (Kalonji)",
    description: "Tiny black seeds used in breads and pickles.",
    price: 110,
    originalPrice: 150,
    image: "https://images.pexels.com/photos/5639979/pexels-photo-5639979.jpeg",
    category: "Seeds",
    stock: 140,
    rating: 4.7,
    numReviews: 19,
    weight: "150g",
    origin: "West Bengal",
    isFeatured: false,
  },
  {
    name: "Sesame Seeds White",
    description: "Nutty flavored white sesame seeds for sweets and cooking.",
    price: 100,
    originalPrice: 140,
    image: "https://images.pexels.com/photos/5639977/pexels-photo-5639977.jpeg",
    category: "Seeds",
    stock: 170,
    rating: 4.8,
    numReviews: 26,
    weight: "200g",
    origin: "Andhra Pradesh",
    isFeatured: true,
  },
  {
    name: "Sesame Seeds Black",
    description: "Rich black sesame seeds packed with nutrients.",
    price: 120,
    originalPrice: 160,
    image: "https://images.pexels.com/photos/1128684/pexels-photo-1128684.jpeg",
    category: "Seeds",
    stock: 150,
    rating: 4.7,
    numReviews: 23,
    weight: "200g",
    origin: "Tamil Nadu",
    isFeatured: false,
  },
  {
    name: "Flax Seeds (Alsi)",
    description: "Healthy omega-3 rich seeds for daily nutrition.",
    price: 80,
    originalPrice: 110,
    image: "https://images.pexels.com/photos/277253/pexels-photo-277253.jpeg",
    category: "Seeds",
    stock: 200,
    rating: 4.6,
    numReviews: 21,
    weight: "250g",
    origin: "Punjab",
    isFeatured: true,
  },
  {
    name: "Chia Seeds",
    description: "Superfood seeds rich in fiber and protein.",
    price: 150,
    originalPrice: 200,
    image: "https://images.pexels.com/photos/4061520/pexels-photo-4061520.jpeg",
    category: "Seeds",
    stock: 130,
    rating: 4.9,
    numReviews: 35,
    weight: "200g",
    origin: "Imported",
    isFeatured: true,
  },
  {
    name: "Watermelon Seeds",
    description: "Crunchy and nutritious seeds ideal for snacking and cooking.",
    price: 140,
    originalPrice: 180,
    image: "https://images.pexels.com/photos/5639975/pexels-photo-5639975.jpeg",
    category: "Seeds",
    stock: 120,
    rating: 4.7,
    numReviews: 18,
    weight: "200g",
    origin: "Rajasthan",
    isFeatured: false,
  },
  {
    name: "Red Chilli Powder",
    description: "Spicy and vibrant red chilli powder for enhancing flavor and color.",
    price: 95,
    originalPrice: 130,
    image: "https://images.pexels.com/photos/277253/pexels-photo-277253.jpeg",
    category: "Ground Spices",
    stock: 180,
    rating: 4.7,
    numReviews: 26,
    weight: "250g",
    origin: "Guntur, Andhra Pradesh",
    isFeatured: true,
  },
  {
    name: "Coriander Powder (Dhania)",
    description: "Freshly ground coriander powder with mild citrus flavor.",
    price: 80,
    originalPrice: 110,
    image: "https://images.pexels.com/photos/1128684/pexels-photo-1128684.jpeg",
    category: "Ground Spices",
    stock: 200,
    rating: 4.6,
    numReviews: 20,
    weight: "250g",
    origin: "Rajasthan",
    isFeatured: false,
  },
  {
    name: "Cumin Powder (Jeera Powder)",
    description: "Aromatic cumin powder perfect for curries and spice blends.",
    price: 105,
    originalPrice: 140,
    image: "https://images.pexels.com/photos/5639981/pexels-photo-5639981.jpeg",
    category: "Ground Spices",
    stock: 170,
    rating: 4.7,
    numReviews: 22,
    weight: "200g",
    origin: "Gujarat",
    isFeatured: true,
  },
  {
    name: "Black Pepper Powder",
    description: "Strong and pungent black pepper powder for seasoning.",
    price: 140,
    originalPrice: 180,
    image: "https://images.pexels.com/photos/5639979/pexels-photo-5639979.jpeg",
    category: "Ground Spices",
    stock: 150,
    rating: 4.8,
    numReviews: 25,
    weight: "200g",
    origin: "Kerala",
    isFeatured: true,
  },
  {
    name: "Dry Mango Powder (Amchur)",
    description: "Tangy amchur powder made from dried raw mangoes.",
    price: 90,
    originalPrice: 120,
    image: "https://images.pexels.com/photos/4061520/pexels-photo-4061520.jpeg",
    category: "Ground Spices",
    stock: 160,
    rating: 4.6,
    numReviews: 19,
    weight: "200g",
    origin: "Uttar Pradesh",
    isFeatured: false,
  },
  {
    name: "Ginger Powder (Saunth)",
    description: "Dry ginger powder used in curries and herbal remedies.",
    price: 100,
    originalPrice: 135,
    image: "https://images.pexels.com/photos/5639980/pexels-photo-5639980.jpeg",
    category: "Ground Spices",
    stock: 140,
    rating: 4.5,
    numReviews: 18,
    weight: "200g",
    origin: "Madhya Pradesh",
    isFeatured: false,
  },
  {
    name: "Garlic Powder",
    description: "Fine garlic powder for quick flavoring in recipes.",
    price: 110,
    originalPrice: 150,
    image: "https://images.pexels.com/photos/5639977/pexels-photo-5639977.jpeg",
    category: "Ground Spices",
    stock: 150,
    rating: 4.6,
    numReviews: 21,
    weight: "200g",
    origin: "Punjab",
    isFeatured: true,
  },
  {
    name: "Onion Powder",
    description: "Dehydrated onion powder for instant cooking convenience.",
    price: 95,
    originalPrice: 130,
    image: "https://images.pexels.com/photos/1128684/pexels-photo-1128684.jpeg",
    category: "Ground Spices",
    stock: 160,
    rating: 4.5,
    numReviews: 17,
    weight: "200g",
    origin: "Maharashtra",
    isFeatured: false,
  },
  {
    name: "Black Pepper Whole",
    description: "Premium whole black peppercorns with strong aroma and sharp flavor.",
    price: 180,
    originalPrice: 220,
    image: "https://images.pexels.com/photos/5639979/pexels-photo-5639979.jpeg",
    category: "Pepper",
    stock: 150,
    rating: 4.8,
    numReviews: 32,
    weight: "200g",
    origin: "Kerala",
    isFeatured: true,
  },
  {
    name: "Black Pepper Powder",
    description: "Finely ground black pepper for seasoning and cooking.",
    price: 170,
    originalPrice: 210,
    image: "https://images.pexels.com/photos/5639979/pexels-photo-5639979.jpeg",
    category: "Pepper",
    stock: 160,
    rating: 4.7,
    numReviews: 28,
    weight: "200g",
    origin: "Kerala",
    isFeatured: true,
  },
  {
    name: "White Pepper Whole",
    description: "Mild and earthy white pepper used in soups and sauces.",
    price: 190,
    originalPrice: 240,
    image: "https://images.pexels.com/photos/277253/pexels-photo-277253.jpeg",
    category: "Pepper",
    stock: 130,
    rating: 4.6,
    numReviews: 20,
    weight: "150g",
    origin: "Tamil Nadu",
    isFeatured: false,
  },
  {
    name: "White Pepper Powder",
    description: "Smooth white pepper powder for delicate flavors.",
    price: 185,
    originalPrice: 230,
    image: "https://images.pexels.com/photos/277253/pexels-photo-277253.jpeg",
    category: "Pepper",
    stock: 120,
    rating: 4.5,
    numReviews: 18,
    weight: "150g",
    origin: "Tamil Nadu",
    isFeatured: false,
  },
  {
    name: "Crushed Black Pepper",
    description: "Coarsely crushed pepper for bold texture and flavor.",
    price: 175,
    originalPrice: 215,
    image: "https://images.pexels.com/photos/5639979/pexels-photo-5639979.jpeg",
    category: "Pepper",
    stock: 140,
    rating: 4.7,
    numReviews: 22,
    weight: "200g",
    origin: "Kerala",
    isFeatured: true,
  },
  {
    name: "Green Peppercorns",
    description: "Fresh green peppercorns preserved for mild spicy taste.",
    price: 200,
    originalPrice: 250,
    image: "https://images.pexels.com/photos/5639981/pexels-photo-5639981.jpeg",
    category: "Pepper",
    stock: 100,
    rating: 4.6,
    numReviews: 16,
    weight: "150g",
    origin: "Karnataka",
    isFeatured: false,
  },
  {
    name: "Mixed Pepper Blend",
    description: "Blend of black, white, and green pepper for balanced flavor.",
    price: 210,
    originalPrice: 260,
    image: "https://images.pexels.com/photos/1128684/pexels-photo-1128684.jpeg",
    category: "Pepper",
    stock: 120,
    rating: 4.8,
    numReviews: 24,
    weight: "200g",
    origin: "India",
    isFeatured: true,
  },
  {
    name: "Organic Black Pepper",
    description: "Certified organic black pepper with strong pungency.",
    price: 220,
    originalPrice: 270,
    image: "https://images.pexels.com/photos/5639979/pexels-photo-5639979.jpeg",
    category: "Pepper",
    stock: 110,
    rating: 4.9,
    numReviews: 30,
    weight: "200g",
    origin: "Kerala",
    isFeatured: true,
  },
  {
    name: "Pepper Powder Extra Strong",
    description: "Highly pungent pepper powder for intense flavor.",
    price: 195,
    originalPrice: 240,
    image: "https://images.pexels.com/photos/277253/pexels-photo-277253.jpeg",
    category: "Pepper",
    stock: 130,
    rating: 4.7,
    numReviews: 21,
    weight: "200g",
    origin: "Kerala",
    isFeatured: false,
  },
  {
    name: "Roasted Pepper Powder",
    description: "Lightly roasted pepper powder for smoky taste.",
    price: 185,
    originalPrice: 230,
    image: "https://images.pexels.com/photos/5639981/pexels-photo-5639981.jpeg",
    category: "Pepper",
    stock: 140,
    rating: 4.6,
    numReviews: 19,
    weight: "200g",
    origin: "Tamil Nadu",
    isFeatured: false,
  },
  {
    name: "Pepper & Salt Mix",
    description: "Balanced mix of pepper and salt for quick seasoning.",
    price: 150,
    originalPrice: 190,
    image: "https://images.pexels.com/photos/1128684/pexels-photo-1128684.jpeg",
    category: "Pepper",
    stock: 160,
    rating: 4.5,
    numReviews: 17,
    weight: "200g",
    origin: "Gujarat",
    isFeatured: false,
  },
  {
    name: "Fine Grind Black Pepper",
    description: "Ultra-fine black pepper powder for smooth texture.",
    price: 180,
    originalPrice: 220,
    image: "https://images.pexels.com/photos/5639979/pexels-photo-5639979.jpeg",
    category: "Pepper",
    stock: 150,
    rating: 4.8,
    numReviews: 23,
    weight: "200g",
    origin: "Kerala",
    isFeatured: true,
  },
  {
    name: "Premium Peppercorn Mix",
    description: "Luxury blend of multicolor peppercorns for gourmet dishes.",
    price: 230,
    originalPrice: 280,
    image: "https://images.pexels.com/photos/5639981/pexels-photo-5639981.jpeg",
    category: "Pepper",
    stock: 100,
    rating: 4.9,
    numReviews: 27,
    weight: "200g",
    origin: "Imported",
    isFeatured: true,
  },
  // Additional products to reach 100+
  {
    name: "Cinnamon Sticks (Dalchini)",
    description: "Aromatic cinnamon sticks for teas, desserts and curries.",
    price: 99,
    originalPrice: 129,
    image: "https://images.pexels.com/photos/5639981/pexels-photo-5639981.jpeg",
    category: "Whole Spices",
    stock: 200,
    rating: 4.7,
    numReviews: 25,
    weight: "100g",
    origin: "Kerala",
    isFeatured: true,
  },
  {
    name: "Cloves (Laung)",
    description: "Strong aromatic cloves for rich flavor in biryani and masalas.",
    price: 149,
    originalPrice: 189,
    image: "https://images.pexels.com/photos/5639979/pexels-photo-5639979.jpeg",
    category: "Whole Spices",
    stock: 150,
    rating: 4.8,
    numReviews: 22,
    weight: "50g",
    origin: "Tamil Nadu",
    isFeatured: true,
  },
  {
    name: "Star Anise (Chakri Phool)",
    description: "Beautiful star-shaped spice with licorice flavor.",
    price: 129,
    originalPrice: 169,
    image: "https://images.pexels.com/photos/5639975/pexels-photo-5639975.jpeg",
    category: "Whole Spices",
    stock: 120,
    rating: 4.6,
    numReviews: 18,
    weight: "50g",
    origin: "Kerala",
    isFeatured: false,
  },
  {
    name: "Mace (Javitri)",
    description: "Delicate spice with warm, nutty flavor.",
    price: 199,
    originalPrice: 249,
    image: "https://images.pexels.com/photos/5639976/pexels-photo-5639976.jpeg",
    category: "Whole Spices",
    stock: 80,
    rating: 4.7,
    numReviews: 15,
    weight: "50g",
    origin: "Kerala",
    isFeatured: false,
  },
  {
    name: "Nutmeg (Jaiphal)",
    description: "Whole nutmeg for grinding fresh in recipes.",
    price: 179,
    originalPrice: 229,
    image: "https://images.pexels.com/photos/5639980/pexels-photo-5639980.jpeg",
    category: "Whole Spices",
    stock: 90,
    rating: 4.7,
    numReviews: 20,
    weight: "100g",
    origin: "Kerala",
    isFeatured: true,
  },
  {
    name: "Bay Leaves (Tej Patta)",
    description: "Fragrant bay leaves for curries and rice dishes.",
    price: 79,
    originalPrice: 109,
    image: "https://images.pexels.com/photos/5639977/pexels-photo-5639977.jpeg",
    category: "Whole Spices",
    stock: 250,
    rating: 4.5,
    numReviews: 28,
    weight: "50g",
    origin: "Himachal Pradesh",
    isFeatured: false,
  },
  {
    name: "Dried Red Chillies",
    description: "Whole dried red chillies for tempering and grinding.",
    price: 89,
    originalPrice: 119,
    image: "https://images.pexels.com/photos/277253/pexels-photo-277253.jpeg",
    category: "Whole Spices",
    stock: 180,
    rating: 4.6,
    numReviews: 22,
    weight: "200g",
    origin: "Andhra Pradesh",
    isFeatured: true,
  },
  {
    name: "Coriander Seeds (Sabut Dhania)",
    description: "Whole coriander seeds for fresh grinding.",
    price: 69,
    originalPrice: 99,
    image: "https://images.pexels.com/photos/1128684/pexels-photo-1128684.jpeg",
    category: "Seeds",
    stock: 220,
    rating: 4.5,
    numReviews: 24,
    weight: "250g",
    origin: "Rajasthan",
    isFeatured: false,
  },
  {
    name: "Chat Masala",
    description: "Tangy and spicy blend for fruits, chaats and snacks.",
    price: 89,
    originalPrice: 119,
    image: "https://images.pexels.com/photos/4061520/pexels-photo-4061520.jpeg",
    category: "Blended Masala",
    stock: 170,
    rating: 4.8,
    numReviews: 35,
    weight: "200g",
    origin: "Delhi",
    isFeatured: true,
  },
  {
    name: "Chai Masala",
    description: "Aromatic spice blend for authentic Indian tea.",
    price: 99,
    originalPrice: 129,
    image: "https://images.pexels.com/photos/5639981/pexels-photo-5639981.jpeg",
    category: "Blended Masala",
    stock: 190,
    rating: 4.7,
    numReviews: 42,
    weight: "150g",
    origin: "Assam",
    isFeatured: true,
  },
  {
    name: "Goda Masala",
    description: "Maharashtrian special sweet spice blend.",
    price: 139,
    originalPrice: 179,
    image: "https://images.pexels.com/photos/5639979/pexels-photo-5639979.jpeg",
    category: "Blended Masala",
    stock: 100,
    rating: 4.6,
    numReviews: 16,
    weight: "200g",
    origin: "Maharashtra",
    isFeatured: false,
  },
  {
    name: "Kolhapuri Masala",
    description: "Spicy and hot blend from Kolhapur region.",
    price: 129,
    originalPrice: 169,
    image: "https://images.pexels.com/photos/5639975/pexels-photo-5639975.jpeg",
    category: "Blended Masala",
    stock: 110,
    rating: 4.7,
    numReviews: 24,
    weight: "200g",
    origin: "Kolhapur",
    isFeatured: true,
  },
  {
    name: "Panch Phoron",
    description: "Bengali five-spice blend of whole seeds.",
    price: 79,
    originalPrice: 109,
    image: "https://images.pexels.com/photos/5639976/pexels-photo-5639976.jpeg",
    category: "Seeds",
    stock: 160,
    rating: 4.5,
    numReviews: 19,
    weight: "200g",
    origin: "West Bengal",
    isFeatured: false,
  },
  {
    name: "Pink Himalayan Salt",
    description: "Mineral-rich pink salt for cooking and finishing.",
    price: 149,
    originalPrice: 199,
    image: "https://images.pexels.com/photos/5639980/pexels-photo-5639980.jpeg",
    category: "Salt",
    stock: 200,
    rating: 4.8,
    numReviews: 38,
    weight: "500g",
    origin: "Himalayas",
    isFeatured: true,
  },
  {
    name: "Black Salt (Kala Namak)",
    description: "Sulfurous black salt for chaats and vegan dishes.",
    price: 69,
    originalPrice: 99,
    image: "https://images.pexels.com/photos/5639977/pexels-photo-5639977.jpeg",
    category: "Salt",
    stock: 180,
    rating: 4.6,
    numReviews: 26,
    weight: "250g",
    origin: "India",
    isFeatured: false,
  },
  {
    name: "Sendha Namak (Rock Salt)",
    description: "Rock salt used during fasting and cooking.",
    price: 59,
    originalPrice: 89,
    image: "https://images.pexels.com/photos/1128684/pexels-photo-1128684.jpeg",
    category: "Salt",
    stock: 220,
    rating: 4.5,
    numReviews: 20,
    weight: "500g",
    origin: "Rajasthan",
    isFeatured: false,
  },
  {
    name: "Asafoetida (Hing)",
    description: "Strong aromatic gum resin used in tempering.",
    price: 89,
    originalPrice: 129,
    image: "https://images.pexels.com/photos/277253/pexels-photo-277253.jpeg",
    category: "Other",
    stock: 140,
    rating: 4.4,
    numReviews: 22,
    weight: "50g",
    origin: "Afghanistan",
    isFeatured: false,
  },
  {
    name: "Dry Ginger Powder",
    description: "Warming ginger powder for teas and curries.",
    price: 99,
    originalPrice: 139,
    image: "https://images.pexels.com/photos/4061520/pexels-photo-4061520.jpeg",
    category: "Ground Spices",
    stock: 150,
    rating: 4.6,
    numReviews: 24,
    weight: "200g",
    origin: "Kerala",
    isFeatured: true,
  },
  {
    name: "Kasuri Methi (Dried Fenugreek)",
    description: "Dried fenugreek leaves for authentic butter chicken.",
    price: 79,
    originalPrice: 109,
    image: "https://images.pexels.com/photos/5639981/pexels-photo-5639981.jpeg",
    category: "Dried Herbs",
    stock: 200,
    rating: 4.7,
    numReviews: 31,
    weight: "100g",
    origin: "Rajasthan",
    isFeatured: true,
  },
  {
    name: "Poppy Seeds (Khus Khus)",
    description: "Small white seeds used in curries and sweets.",
    price: 119,
    originalPrice: 159,
    image: "https://images.pexels.com/photos/5639979/pexels-photo-5639979.jpeg",
    category: "Seeds",
    stock: 130,
    rating: 4.5,
    numReviews: 17,
    weight: "200g",
    origin: "Madhya Pradesh",
    isFeatured: false,
  },
  {
    name: "Pomegranate Seeds (Anardana)",
    description: "Dried pomegranate seeds for tangy flavor.",
    price: 159,
    originalPrice: 199,
    image: "https://images.pexels.com/photos/5639975/pexels-photo-5639975.jpeg",
    category: "Seeds",
    stock: 100,
    rating: 4.7,
    numReviews: 23,
    weight: "150g",
    origin: "Himachal Pradesh",
    isFeatured: true,
  }
];

const seed = async () => {
  try {
    await mongoose.connect(
      "mongodb://masalahub:masala123@ac-herrj0t-shard-00-00.bu1rdn0.mongodb.net:27017,ac-herrj0t-shard-00-01.bu1rdn0.mongodb.net:27017,ac-herrj0t-shard-00-02.bu1rdn0.mongodb.net:27017/masalaDB?ssl=true&replicaSet=atlas-jlagbm-shard-0&authSource=admin&retryWrites=true&w=majority"
    );

    await Product.deleteMany({});
    await Product.insertMany(products);

    console.log(`✅ ${products.length} Products seeded successfully!`);
    process.exit();
  } catch (err) {
    console.error("❌ Seed error:", err.message);
    process.exit(1);
  }
};

seed();



















